name: Release LIG Arduino Library

on:
  push:
    tags:
      - 'LIG@*'

permissions:
  contents: write

jobs:
  release:
    name: Create GitHub Release for LIG Arduino Library
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: extract
        run: echo "VERSION=${GITHUB_REF#refs/tags/LIG@}" >> $GITHUB_ENV

      - name: Validate Arduino library
        uses: arduino/arduino-lint-action@v2
        with:
          recursive: true

      - name: Zip LIG Arduino Library folder for release
        run: |
          zip -r ../LIG-${{ env.VERSION }}.zip .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: LIG Arduino Library v${{ env.VERSION }}
          tag_name: LIG@${{ env.VERSION }}
          files: LIG-${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
